config/routes.rb
Rails.application.routes.draw do
  resources :emprunts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :livres
  post '/livres/tabledit' => 'livres#tabledit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emprunt.rb
class Emprunt < ApplicationRecord
end

app/models/livre.rb
class Livre < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emprunts_controller.rb
class EmpruntsController < ApplicationController
  before_action :set_emprunt, only: [:show, :edit, :update, :destroy]

  # GET /emprunts
  # GET /emprunts.json
  def index
    @emprunts = Emprunt.all
  end

  # GET /emprunts/1
  # GET /emprunts/1.json
  def show
  end

  # GET /emprunts/new
  def new
    @emprunt = Emprunt.new
  end

  # GET /emprunts/1/edit
  def edit
  end

  # POST /emprunts
  # POST /emprunts.json
  def create
    @emprunt = Emprunt.new(emprunt_params)

    respond_to do |format|
      if @emprunt.save
        format.html { redirect_to @emprunt, notice: 'Emprunt was successfully created.' }
        format.json { render :show, status: :created, location: @emprunt }
      else
        format.html { render :new }
        format.json { render json: @emprunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emprunts/1
  # PATCH/PUT /emprunts/1.json
  def update
    respond_to do |format|
      if @emprunt.update(emprunt_params)
        format.html { redirect_to @emprunt, notice: 'Emprunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @emprunt }
      else
        format.html { render :edit }
        format.json { render json: @emprunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emprunts/1
  # DELETE /emprunts/1.json
  def destroy
    @emprunt.destroy
    respond_to do |format|
      format.html { redirect_to emprunts_url, notice: 'Emprunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emprunt
      @emprunt = Emprunt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emprunt_params
      params.require(:emprunt).permit(:idlivre, :nombre)
    end
end

app/controllers/livres_controller.rb
class LivresController < ApplicationController
  before_action :set_livre, only: [:show, :edit, :update, :destroy]

  def index
    @livres = Livre.order(id: :desc)
  end

  def new
    @livre = Livre.new
  end

  def edit
  end

  def create
    @livre = Livre.new(livre_params)
    respond_to do |format|
      if @livre.save(livre_params)
        format.js
        format.html { redirect_to livres_path, notice: 'livre was successfully added.' }
        format.json { render :index, status: :ok, location: livres_path }
      else
        format.html { render :new }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @livre.update(livre_params)
          format.js
          format.html { redirect_to @livre, success: 'livre mis à jour' }
          format.json { render :index, status: :ok, location: livres_path }
      else
        format.html { render edit_livre_path(@livre) }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # interaction avec table-edit
=begin
  def tabledit
    if params[:edit]
      @livre = Livre.find(params[:id])
      respond_to do |format|
        if @livre.update(livre_params)
          format.html { redirect_to @livre, notice: 'livre was successfully updated.' }
          format.json { render :index, status: :ok, location: livres_path }
        else
          format.html { render :edit }
          format.json { render json: @livre.errors, status: :unprocessable_entity }
        end
      end
    end
  end
=end

  def destroy
    @livre.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to livres_url, success: 'livre supprimé' }
      format.json { head :no_content }
    end
    #redirect_to livres_url, success: 'livre supprimé' 
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_livre
    @livre = Livre.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def livre_params
    params.require(:livre).permit(
      :titre,
      :auteur,
      :synopsis,
      :style,
      :isbn
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emprunts_helper.rb
module EmpruntsHelper
end

app/helpers/livres_helper.rb
module LivresHelper
  def link_to_add_book(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/emprunts/_form.html.erb
<%= form_with(model: emprunt, local: true) do |form| %>
  <% if emprunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emprunt.errors.count, "error") %> prohibited this emprunt from being saved:</h2>

      <ul>
      <% emprunt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idlivre %>
    <%= form.number_field :idlivre %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.number_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emprunts/edit.html.erb
<h1>Editing Emprunt</h1>

<%= render 'form', emprunt: @emprunt %>

<%= link_to 'Show', @emprunt %> |
<%= link_to 'Back', emprunts_path %>

app/views/emprunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emprunts</h1>

<table>
  <thead>
    <tr>
      <th>Idlivre</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emprunts.each do |emprunt| %>
      <tr>
        <td><%= emprunt.idlivre %></td>
        <td><%= emprunt.nombre %></td>
        <td><%= link_to 'Show', emprunt %></td>
        <td><%= link_to 'Edit', edit_emprunt_path(emprunt) %></td>
        <td><%= link_to 'Destroy', emprunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emprunt', new_emprunt_path %>

app/views/emprunts/new.html.erb
<h1>New Emprunt</h1>

<%= render 'form', emprunt: @emprunt %>

<%= link_to 'Back', emprunts_path %>

app/views/emprunts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idlivre:</strong>
  <%= @emprunt.idlivre %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @emprunt.nombre %>
</p>

<%= link_to 'Edit', edit_emprunt_path(@emprunt) %> |
<%= link_to 'Back', emprunts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajaxtable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="mainmenu" role="navigation">
        <a class="navbar-brand" href="/livres/index">Essai de tableau éditable en Rails</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav ml-auto">
          </ul>
        </div>
      </nav>
    </header>

    <main class="mx-5">

      <%= yield %>

    </main>
    <%#= javascript_include_tag 'livres.js' %>
  </body>
</html>

app/views/livres/_form.html.erb
<%= form_with(model: livre, local: true, remote: true, class: "mts") do |form| %>
  <% if livre.errors.any? %>
    <div class="card text-white bg-danger mb-2">
      <div class="card-header">
        <%= pluralize(livre.errors.count, "error") %> prohibited this livre from being saved:
      </div>
      <div class="card-body">
        <ul>
          <% livre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= form.text_field :titre, placeholder: :titre %>

  <%= form.text_field :auteur, placeholder: :auteur %>

  <%= form.text_field :synopsis, placeholder: :synopsis %>

  <%= form.text_field :style, placeholder: :style %>

  <%= form.text_field :isbn, placeholder: :isbn %>

  <%= form.submit :submit %>
<% end %>

app/views/livres/_livre.html.erb
<tr>
  <td><%= livre.titre %></td>
  <td><%= livre.auteur %></td>
  <td><%= livre.synopsis[0..120] %></td>
  <td><%= livre.style %></td>
  <td><%= livre.isbn %></td>
  <td>
    <%= link_to 'Edit', edit_livre_path(livre), remote: true %>
    <%= link_to 'Destroy', livre, method: :delete, data: { confirm: 'Supprimer la donnée de façon définitive ?', remote: true }, class: 'delete' %>
  </td>
</tr>

app/views/livres/create.js.erb
$('table#livres > tbody form').remove();
$('#new-book a').show();
$('table#livres tbody').prepend('<%= j render @livre %>');

app/views/livres/destroy.js.erb
$('.delete').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
});

app/views/livres/edit.html.erb
<h1 class="txtcenter"><%= @livre.titre %></h1>

<%= render 'form', livre: @livre %>

app/views/livres/index.html.erb
<h1>Tableau de mes livres</h1>

<% if @livres.size > 0 %>
  <div class="table-responsive">
    <table id="livres" class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Titre</th>
          <th>Auteur</th>
          <th>Synopsis</th>
          <th>Style</th>
          <th>ISBN</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <%= render @livres %>
      </tbody>
    </table>
  </div>
<% end %>

<div id="new-book">
  <%= link_to 'Nouveau livre', new_livre_path, remote: true %>
</div>

app/views/livres/new.html.erb
<h1 class="txtcenter">Nouveau livre</h1>

<%= render 'form', livre: @livre %>

app/views/livres/new.js.erb
$('#new-book a').hide().parent().append("<%= j render 'form', livre: @livre %>");

app/views/livres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre :</strong>
  <%= @livre.titre %>
</p>

<p>
  <strong>Auteur :</strong>
  <%= @livre.auteur %>
</p>

<p>
  <strong>Synopsis :</strong>
  <%= @livre.synopsis %>
</p>

<p>
  <strong>Style :</strong>
  <%= @livre.style %>
</p>

<p>
  <strong>ISBN :</strong>
  <%= @livre.isbn %>
</p>

<%= link_to 'Edit', edit_livre_path(@livre) %> |
<%= link_to 'Back', livres_path %>